THIRDPARTY:
  URL: "https://run.mocky.io/v3/87931203-8086-43ef-ba16-4c8903d8fa88"
DATA:
  USERFILENAME: "./data/users.csv"
  USERTAGSFILENAME: "./data/usertags.csv"
  USERFRIENDSFILENAME: "./data/userfriends.csv"